spring.application.name=Com.self.SpringBoot-SecurityBasicAuthentication


server.port=8888
server.servlet.context-path=/secure

#databse prpoperties
spring.datasource.url=jdbc:mysql://localhost:3306/product
spring.datasource.username=root
spring.datasource.password=Shiva@#$&1232

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=admin
spring.security.user.password=1234