spring.application.name=Com.self.Value-Annotation


order.id=1501
order.name=Vivo
order.delivery.charge=15
order.passcode=45143

app.email.Host=Self@gmail.com
app.email.User=ksk@gmail.com
app.email.Password=ksk69